# *** Serrapilheira/ICTP-SAIFR training program ***
# Module 1: Quantitative Methods
# Topic: Fluctuations and the Nature of Mutations
#************************************************
#Ruth Corona Moreno
# ---------------------------------------------------------------

#Packages
library(ggplot2)
library(stats)


# -----------------------Warm up ----------------------------------------
#Randomly sample a number between 0 and 1:
runif(1)

#Generating multiple random numbers:
randvec = runif(100)

#Generate a random matrix of size mxn array:
randarray = matrix(runif(100),nrow=10,ncol=10)

# ---------------------------------------------------------------
#Chalenge 1: Properties of Random Distributions
#**********************************************
#What is the mean value of a single instance of invoking runif? Similarly, what is the variance? 
#[ANSWER:] runif correspond to a uniform distribution between 0 and 1. So, the mean=1/2, var=1/12

#Once you have identified the mean and variance, plot the distribution of numbers generated by runif by sampling a large
#number of points (10^4) and then using the ggplot2 geom_histogram function to generate a histogram. 
#What shape is the distribution? How does it change as you change the number of bins for the histogram?
#[ANSWER:] 
data_unif = runif(10^4)

ggplot() +
  aes(x=data_unif) +
  geom_histogram(col="black", 
                 fill="gray", 
                 alpha = .5) + 
  labs(title="Histogram data_unif", y="Count")


# ---------------------------------------------------------------
#Standard normal distribution with a mean of 20 and standard deviation of 5
data_norm=rnorm(10^4, mean=20, sd=5)

ggplot() +
  aes(x=data_norm) +
  geom_histogram(col="black", 
                 fill="gray", 
                 alpha = .5) + 
  labs(title="Histogram data_norm", x="Value", y="Count")


#Poisson distribution with rate parameter λ = 20
data_pois=rpois(10^7, 20)

ggplot() +
  aes(x=data_pois) +
  geom_histogram(col="black", 
                 fill="gray", 
                 alpha = .5) + 
  labs(title="Histogram data_pois", x="Value", y="Count")


# ---------------------------------------------------------------
#Chalenge 2: Random number generation
#**********************************************
#The following problems focus on modifying the mean and ranges of random numbers by modulating the output
#of built-in random number functions.
#* Generate 1000 random numbers equally spaced between 0 to 5.
#* Generate 1000 random numbers equally spaced between 2 to 7.
#* Generate 1000 random numbers equally spaced between -5 to 5.
#In each of these cases, use the command rand(1,1000) and then simple arithmetic (i.e., addition, subtraction,
#and multiplication) to transform the random numbers to specified ranges. You can do it!
#[Answer:]
#?????




# ---------------------------------------------------------------
#Chalenge 3: Comparing exponential random sampling
#**********************************************
#Compare the distribution of 10^3 exponentially distributed random numbers using the cdf-based method to the
#distribution using the following built-in R command:

my_lambda = 1/10
n=10**3

#Random numbers following exponential distribution generated by a function of R
Rexprnd = rexp(n,my_lambda)

#Random numbers following exponential distribution generated by a our function
rand2exp = function(probsamp,my_lambda){
  # function exprand = rand2exp(probsamp,lambda)
  # lambda is the rate of the Markov process
  # probsamp are uniformly randomly sampled numbers
  return(-1/my_lambda*log(1-probsamp))
}

probsamp = runif(n)
expprobsamp = rand2exp(probsamp,my_lambda)

#Comparison plots
CDF_Rexprnd=ecdf(Rexprnd)
CDF_expprobsamp=ecdf(expprobsamp)

test2 <- rbind(multistakeuserutil,reguserUtil)

plot(hist_Rexprnd$density, type='b')  # first histogram
plot(hist_expprobsamp, col=rgb(1,0,0,1/4), xlim=c(0,10), add=T)  # second

plot(CDF_Rexprnd, xlab = "Value, x",
     ylab = "CDF, P(x)", main="") #, main="Nos"
lines(CDF_expprobsamp, type='b', col='red')
legend("right", legend=c("Custom method", "Built-in method"),
       col=c("red", "black"), lty = 1:2, cex=0.8)

